### PR TITLE
[WIP] Add stable memory variant

### PR DESCRIPTION
**Pull request by Trolldemorted**
This is my current status of a stable memory region. It is able to reliably pop into pc, but it has a few issues:

- when writing it does not check whether the value overlaps another value
- when reading a value which does not exist or has an insufficient width it does not return a properly constrained symbol, and it does not save that symbol in its HashMap

Does this roughly match what you had in mind in #16?

### CODE REVIEW

**Comment by Alasdair** [comment]
I've been working on support for ARMv8 address translation, and I didn't want to describe the in-memory format of a specific architecture's page tables in the core library so I added a mechanism for defining custom memory regions using a trait object:

https://github.com/rems-project/isla/blob/f26cf2797efa22d37445f9287b35fa3dfbb942f6/isla-lib/src/memory.rs#L56

**Comment by Trolldemorted** [comment]
>I've been working on support for ARMv8 address translation

For general support for address translations or for the easy creation of page tables in the emulator? After stepping through the memory access code of sail-arm in isla I had the impression that the page tables are interpreted correctly.

>It's in a separate branch right now but eventually I will merge it in once I've cleaned it up

👍 looking forward to it! Nevertheless you might want to have a stable memory region upstream (assuming that you are planning to only have the trait definition in isla-lib), I suspect I won't be the only one who wants to pop from a stack into pc.

I have been thinking it might be easier to only save symbols and vals with 8bit width to the memory (deconstruct when writing, reconstruct when reading), because it makes the "didn't find the value directly -> now I have to try to the left and to the right and merge the Val" - problem go away. What do you think? It has the obvious downside of more symbols load.

**Comment by Alasdair** [comment]
> For general support for address translations or for the easy creation of page tables in the emulator? After stepping through the memory access code of sail-arm in isla I had the impression that the page tables are interpreted correctly.

For easy creation of page tables mostly

**Comment by Trolldemorted** [comment]
Closing because things have changed with the new memory

**Pull request closed without merging**
